# This workflow will build a Java project with Maven

name: Build and Unit tests

on:
  push:
    branches:
      - 'master'
      - "[0-9]+.[0-9]+.x"
  pull_request:
    branches:
      - 'master'
      - "[0-9]+.[0-9]+.x"
    types: [ opened, reopened, synchronize ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write      
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@v1        
    
    - name: Cache m2 repo
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
        
    - name: Extract Maven project version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: project      
    
    - name: Build and run Unit tests
      run: |
        mvn --batch-mode install --file pom.xml --no-transfer-progress -Dno-format -P docker -Ddocker.organization=${{secrets.IMAGE_REPO_HOSTNAME}}
        docker login -u="${{secrets.IMAGE_REPO_USERNAME}}" -p="${{secrets.IMAGE_REPO_PASSWORD}}" ${{secrets.IMAGE_REPO_HOSTNAME}}
        docker push ${{secrets.IMAGE_REPO_HOSTNAME}}/${{secrets.IMAGE_REPO_NAMESPACE}}/openmessaging-benchmark:${{steps.metadata.outputs.version}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
